# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-10 22:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.IntegerField()),
                ('idviber', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dtime', models.DateTimeField()),
                ('message_token', models.CharField(max_length=19)),
                ('idviber', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='messagestatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_token', models.CharField(max_length=19)),
                ('user_id', models.CharField(max_length=24)),
                ('status', models.CharField(max_length=12)),
                ('dtime', models.DateTimeField(default=datetime.datetime(2017, 11, 11, 1, 23, 29, 692190))),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesttext', models.TextField()),
                ('DateTimeField', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='viberid',
            fields=[
                ('idviber', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('subscribed', models.BooleanField()),
                ('name', models.CharField(default='oleg', max_length=24)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
