# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-02 22:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viberapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLinkToId',
            fields=[
                ('lschet', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('current', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='sessionstate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=24)),
                ('data1', models.CharField(max_length=24)),
                ('data2', models.CharField(max_length=24)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='telegrammchatid',
            fields=[
                ('chatid', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(default='oleg', max_length=24)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='tokenToSnapping',
            fields=[
                ('lschet', models.IntegerField(primary_key=True, serialize=False)),
                ('tokenid', models.IntegerField()),
                ('name', models.CharField(max_length=24)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='Messanger',
            field=models.CharField(default='viber', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='Messanger',
            field=models.CharField(default='viber', max_length=20),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='dtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 3, 1, 34, 16, 180207)),
        ),
    ]
