# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-03 10:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viberapp', '0002_auto_20180103_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('abonstation', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=300)),
                ('Tel', models.CharField(max_length=100)),
                ('WorkTime', models.CharField(max_length=100)),
                ('latGPS', models.CharField(default=0, max_length=100)),
                ('longGPS', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OopsEventsOfReq',
            fields=[
                ('chatid', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='dtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 3, 13, 42, 4, 309179)),
        ),
    ]
