# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-03 10:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viberapp', '0005_auto_20180103_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestatus',
            name='dtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 3, 13, 48, 22, 904644)),
        ),
    ]
