# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-03 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viberapp', '0006_auto_20180103_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokentosnapping',
            name='messanger',
            field=models.CharField(default='telegram', max_length=24, primary_key=True),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='dtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 3, 14, 18, 46, 82909)),
        ),
    ]
